# Runs notebooks as a test nighly.
name: Notebooks nightly test

on:
  schedule:
    - cron: '0 6 * * *' #  6AM UTC
  workflow_dispatch:

jobs:
  notebooks_test:
      name: Test notebooks
      runs-on: ubuntu-latest

      steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Setup requirements
        run: |
            python -m pip install pytest nbmake

      - name: Run notebooks as a test
        run: |
            pytest --nbmake "./tutorials/"
        env:
          TEST_SHAPED_API_KEY: ${{ secrets.SHAPED_API_KEY_NOTEBOOKS_TEST }}
