# Runs notebooks as a test nighly.
name: Notebooks nightly test

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 6 * * *' #  6AM UTC
  workflow_dispatch:

jobs:
  deploy_dev:
      name: Dev deployment
      runs-on: ubuntu-latest

      steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        if: "${{ inputs.deploy_dev }} || ${{ github.event_name == 'schedule' }}"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Setup requirements
        run: |
            python -m pip install pytest nbmake

      - name: Run notebooks as a test
        run: |
            pytest --nbmake "./tutorials/"