# Runs notebooks as a nightly test
name: Notebooks nightly test

on:
  schedule:
    - cron: '0 6 * * *' #  6AM UTC
  workflow_dispatch:

jobs:
  notebooks_test:
      name: Test notebooks
      runs-on: ubuntu-latest

      steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Setup requirements
        run: |
            python -m pip install pytest nbmake

      - name: Run notebooks as a test
        run: |
            pytest --nbmake "./tutorials/"
        env:
          YOUR_API_KEY: ${{ secrets.SHAPED_API_KEY_NOTEBOOKS_TEST }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_NOTEBOOKS_TEST }} 
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_NOTEBOOKS_TEST }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE_NOTEBOOKS_TEST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_NOTEBOOKS_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_NOTEBOOKS_TEST }}