# Runs notebooks as a nightly test
name: Notebooks nightly test

on:
  schedule:
    - cron: '0 6 * * *' #  6AM UTC
  workflow_dispatch:

jobs:
  notebooks_test:
      name: Test notebooks
      runs-on: ubuntu-latest

      steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Setup requirements
        run: |
            python -m pip install pytest nbmake pytest-xdist shaped

      - name: Run notebooks as a test
        run: |
            pytest -n=auto --nbmake "./tutorials/"
        env:
          TEST_SHAPED_API_KEY: ${{ secrets.SHAPED_API_KEY_NOTEBOOKS_TEST }}
          TEST_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_NOTEBOOKS_TEST }} 
          TEST_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT_NOTEBOOKS_TEST }}
          TEST_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE_NOTEBOOKS_TEST }}
          TEST_POSTGRES_USER: ${{ secrets.POSTGRES_USER_NOTEBOOKS_TEST }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_NOTEBOOKS_TEST }}

      - name: Clean up notebook artifacts
        run: |
          shaped init --api-key ${{ secrets.SHAPED_API_KEY_NOTEBOOKS_TEST }}
          models=$(shaped list-models)
          
          datasets=$(shaped list-dataset)

          rm -r notebook_assets